@TrainMaster.API_HostAddress = http://localhost:5212

POST {{TrainMaster.API_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Leticia Alves",
  "email": "leticia@email.com",
  "password": "Senha@123",
  "birthday": "2005-07-10T00:00:00Z",
  "goal": 1
}

###

POST {{TrainMaster.API_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@email.com",
  "password": "Senha@123"
}